@api = http://localhost:3000/materiales

GET {{api}}

###
GET {{api}}/35

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
"nombre":"Bicapa",
"descripcion":"Bicapa de 1mm de espesor de color oro",
"espesor":"1",
"longitud_ancho":"0.61",
"longitud_largo":"1.20",
"calidad_material":"Bueno",
"costo_total":"156",
"costo_m2":"1",
"costo_ml":"1",
"cantidad":"2",
"color":"Oro"
}

###
DELETE {{api}}/3

###
PUT {{api}}/30
Content-Type: application/json

{
"nombre":"PVC",
"descripcion":"PVC de color negro 5 mm de espesor",
"espesor":"5",
"longitud_ancho":"1.22",
"longitud_largo":"2.44",
"calidad_material":"Bueno",
"costo_total":"120",
"costo_m2":"45.4",
"costo_ml":"49.1",
"color":"Negro"
}
