@api = http://localhost:3000/materialestrabajosrealizados

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{  
"id_orden"    : "1",
"nombre"      : "Acrilico",
"espesor"     : "5",
"color"       : "Transparente", 
"descripcion" : "Acrilico color tranparente", 
"medida_largo": "2", 
"medida_ancho": "3", 
"precio_largo": "32", 
"precio_m2"   : "25", 
"precio_total": "25"
}

###
GET {{api}}/5

###
DELETE {{api}}/5
